# Project name and version
name: 'dbt_src'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_src'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring quoting in this project
quoting:
  database: false
  schema: false
  identifier: false


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  +start: Jan 1 2024
  dbt_src:
    # Config indicated by + and applies to all files under models/example/
    consumer:
      bronze:
        schema: bronze
        +materialized: table
      silver:
        schema: silver
        +materialized: table
      gold:
        schema: gold
        +materialized: table
