SELECT 
    TRIM("CAMPAIGN_ID") AS "CAMPAIGN_ID",
    TRIM(UPPER("CAMPAIGN_NAME")) AS "CAMPAIGN_NAME",
    TRIM("CAMPAIGN_DESCRIPTION") AS "CAMPAIGN_DESCRIPTION",
    "START_DATE",
    "END_DATE",
    TRIM(UPPER("CAMPAIGN_TYPE")) AS "CAMPAIGN_TYPE",
    TRIM(UPPER("CHANNEL")) AS "CHANNEL",
    TRIM(UPPER("CAMPAIGN_STATUS")) AS "CAMPAIGN_STATUS",
    "CREATED_AT",
    "UPDATED_AT",
    "DELETED_AT"
FROM {{ ref('campaigns_bronze') }}