SELECT
    TRIM(UPPER("CUST_ID")) AS "CUST_ID",
    TRIM(UPPER("FIRST_NAME")) AS "FIRST_NAME",
    TRIM(UPPER("LAST_NAME")) AS "LAST_NAME",
    TRIM(UPPER("EMAIL")) AS "EMAIL",
    TRIM(REGEXP_REPLACE("PHONE", '[^0-9]','')) AS "PHONE",
    "DOB",
    TRIM(UPPER("MARITAL_STATUS")) AS "MARITAL_STATUS",
    TRIM(UPPER("ADDRESS")) AS "ADDRESS",
    TRIM(UPPER("CITY")) AS "CITY",
    TRIM(UPPER("COUNTY")) AS "COUNTY",
    TRIM(UPPER("STATE_PROVINCE")) AS "STATE_PROVINCE",
    TRIM("POSTAL_CODE") AS "POSTAL_CODE",
    TRIM(UPPER("COUNTRY")) AS "COUNTRY",
    "IS_ACTIVE",
    "CREATED_AT",
    "UPDATED_AT",    
    "DELETED_AT"
FROM {{ ref('customers_bronze') }}