SELECT
    TRIM(UPPER("LOYALTY_ID")) AS "LOYALTY_ID",
    TRIM(UPPER("CUST_ID")) AS "CUST_ID",
    TRIM(UPPER("PROGRAM_NAME")) AS "PROGRAM_NAME",
    "ENROLLMENT_TMSTP",
    "CURRENT_POINTS_BALANCE",
    TRIM(UPPER("TIER_LEVEL")) AS "TIER_LEVEL",
    "CREATED_AT",
    "UPDATED_AT",
    "DELETED_AT"
FROM {{ ref('loyalty_bronze') }}