SELECT
    TRIM(UPPER("PRODUCT_ID")) AS "PRODUCT_ID",
    TRIM(UPPER("PRODUCT_NAME")) AS "PRODUCT_NAME",
    TRIM(UPPER("PRODUCT_DESCRIPTION")) AS "PRODUCT_DESCRIPTION",
    TRIM(UPPER("PRODUCT_CATEGORY")) AS "PRODUCT_CATEGORY",
    TRIM(UPPER("PRODUCT_SUBCATEGORY")) AS "PRODUCT_SUBCATEGORY",
    "PRODUCT_PRICE",
    "PRODUCT_QTY",
    "IS_ACTIVE",
    TRIM(UPPER("COUNTRY")) AS "COUNTRY",
    "CREATED_AT",
    "UPDATED_AT",
    "DELETED_AT"
FROM {{ ref('products_bronze') }}