SELECT
    TRIM(UPPER("STORE_ID")) AS "STORE_ID",
    TRIM(UPPER("STORE_NAME")) AS "STORE_NAME",
    TRIM(UPPER("STORE_TYPE")) AS "STORE_TYPE",
    TRIM(UPPER("ADDRESS")) AS "ADDRESS",
    TRIM(UPPER("CITY")) AS "CITY",
    TRIM(UPPER("STATE_PROVINCE")) AS "STATE_PROVINCE",
    TRIM("POSTAL_CODE") AS "POSTAL_CODE",
    TRIM(UPPER("COUNTRY")) AS "COUNTRY",
    TRIM(REGEXP_REPLACE("PHONE", '[^0-9]','')) AS "PHONE",
    TRIM(UPPER("EMAIL")) AS "EMAIL",
    "IS_ACTIVE",
    TRIM(UPPER("STORE_MANAGER")) AS "STORE_MANAGER",
    "CREATED_AT",
    "UPDATED_AT",
    "DELETED_AT"
FROM {{ ref('stores_bronze') }}