SELECT 
    CAST("CAMPAIGN_ID" AS VARCHAR(25)) AS "CAMPAIGN_ID",
    CAST("CAMPAIGN_NAME" AS VARCHAR(100)) AS "CAMPAIGN_NAME",
    CAST("CAMPAIGN_DESCRIPTION" AS VARCHAR) AS "CAMPAIGN_DESCRIPTION",
    CAST("START_DATE" AS DATE) AS "START_DATE",
    CAST("END_DATE" AS DATE) AS "END_DATE",
    CAST("CAMPAIGN_TYPE" AS VARCHAR(25)) AS "CAMPAIGN_TYPE",
    CAST("CHANNEL" AS VARCHAR(25)) AS "CHANNEL",
    CAST("CAMPAIGN_STATUS" AS VARCHAR(25)) AS "CAMPAIGN_STATUS",
    CAST("CREATED_AT" AS TIMESTAMP) AS "CREATED_AT",
    TRY_CAST("UPDATED_AT" AS TIMESTAMP) AS "UPDATED_AT",
    TRY_CAST("DELETED_AT" AS TIMESTAMP) AS "DELETED_AT"
FROM {{ source('campaigns_raw', 'campaignsynthdata') }}