SELECT
    CAST("LOYALTY_ID" AS VARCHAR(25)) AS "LOYALTY_ID",
    CAST("CUST_ID" AS VARCHAR) AS "CUST_ID",
    CAST("PROGRAM_NAME" AS VARCHAR(100)) AS "PROGRAM_NAME",
    CAST("ENROLLMENT_TMSTP" AS TIMESTAMP) AS "ENROLLMENT_TMSTP",
    CAST("CURRENT_POINTS_BALANCE" AS INTEGER) AS "CURRENT_POINTS_BALANCE",
    CAST("TIER_LEVEL" AS VARCHAR(25)) AS "TIER_LEVEL",
    CAST("CREATED_AT" AS TIMESTAMP) AS "CREATED_AT",
    TRY_CAST("UPDATED_AT" AS TIMESTAMP) AS "UPDATED_AT",
    TRY_CAST("DELETED_AT" AS TIMESTAMP) AS "DELETED_AT"
FROM {{ source('loyalty_raw', 'loyaltysynthdata') }}