SELECT
    CAST("PRODUCT_ID" AS VARCHAR(50)) AS "PRODUCT_ID",
    CAST("PRODUCT_NAME" AS VARCHAR(100)) AS "PRODUCT_NAME",
    CAST("PRODUCT_DESCRIPTION" AS VARCHAR) AS "PRODUCT_DESCRIPTION",
    CAST("PRODUCT_CATEGORY" AS VARCHAR(50)) AS "PRODUCT_CATEGORY",
    CAST("PRODUCT_SUBCATEGORY" AS VARCHAR(50)) AS "PRODUCT_SUBCATEGORY",
    CAST("PRODUCT_PRICE" AS DECIMAL(10, 2)) AS "PRODUCT_PRICE",
    CAST("PRODUCT_QTY" AS INT) AS "PRODUCT_QTY",
    CAST("IS_ACTIVE" AS BOOLEAN) AS "IS_ACTIVE",
    CAST("COUNTRY" AS VARCHAR(75)) AS "COUNTRY",
    CAST("CREATED_AT" AS TIMESTAMP) AS "CREATED_AT",
    TRY_CAST("UPDATED_AT" AS TIMESTAMP) AS "UPDATED_AT",
    TRY_CAST("DELETED_AT" AS TIMESTAMP) AS "DELETED_AT"
FROM {{ source('products_raw', 'productsynthdata') }}