
version: 2

sources:
  - name: customers_raw
    database: "{{ target.database }}"
    schema: raw
    tables:
      - name: customersynthdata
  - name: products_raw
    database: "{{ target.database }}"
    schema: raw
    tables:
      - name: productsynthdata
  - name: orders_raw
    database: "{{ target.database }}"
    schema: raw
    tables:
      - name: orderssynthdata
  - name: stores_raw
    database: "{{ target.database }}"
    schema: raw
    tables:
      - name: storesynthdata
  - name: loyalty_raw
    database: "{{ target.database }}"
    schema: raw
    tables:
      - name: loyaltysynthdata
  - name: campaigns_raw
    database: "{{ target.database }}"
    schema: raw
    tables:
      - name: campaignsynthdata

models:
  - name: customers_bronze
    description: "Example of a customer input master data schema"
    columns:
      - name: cust_id
        description: "The primary key for this table, represents a unique customer"
      - name: first_name
        description: "The first name of the customer"
      - name: last_name
        description: "The last name of the customer"
      - name: email
        description: "The email address of the customer"
      - name: phone
        description: "The phone number of the customer"
      - name: dob
        description: "The date of birth of the customer"
      - name: marital_status
        description: "The marital status of the customer"
      - name: address
        description: "The address of the customer"
      - name: city
        description: "The city of the customer"
      - name: county
        description: "The county of the customer"
      - name: state_province 
        description: "The state or province of the customer"
      - name: postal_code 
        description: "The postal code code of the customer"
      - name: country 
        description: "The country of the customer"
      - name: is_active
        description: "Flag to indicate if the record is active"
      - name: created_at
        description: "The timestamp of when the record was created"
      - name: updated_at        
        description: "The timestamp of when the record was last updated"
      - name: deleted_at
        description: "The timestamp of when the record was deleted"
  
  - name: products_bronze
    description: "Example of a product master data schema"
    columns:
      - name: product_id
        description: "The primary key for this table, represents a unique product"
      - name: product_name
        description: "The name of the product"
      - name: product_description
        description: "The description of the product"
      - name: product_category
        description: "The category of the product"
      - name: product_subcategory
        description: "The subcategory of the product"
      - name: product_price
        description: "The price of the product"
      - name: product_qty
        description: "The quantity of the product"
      - name: is_active
        description: "Flag to indicate if the record is active"
      - name: country
        description: "The country of the product"
      - name: created_at
        description: "The timestamp of when the record was created"
      - name: updated_at
        description: "The timestamp of when the record was last updated"
      - name: deleted_at
        description: "The timestamp of when the record was deleted"

  - name: orders_bronze
    description: "Example of a orders transactional table schema"
    columns:
      - name: order_id
        description: "The primary key for this table, represents a unique order"
      - name: cust_id
        description: "The foreign key to the customer table"
      - name: product_id
        description: "The foreign key to the product table"
      - name: store_id
        description: "The store id where the order was placed"
      - name: order_tmstp
        description: "The date the order was placed"
      - name: order_total
        description: "The total amount of the order"
      - name: order_qty
        description: "The quantity of the order"
      - name: payment_method
        description: "The payment method of the order"
      - name: order_status
        description: "The status of the order"
      - name: purchase_channel
        description: "The channel the order was purchased from"
      - name: campaign_id
        description: "The campaign id associated with the order"
      - name: ship_address
        description: "The shipping address of the order"
      - name: ship_city
        description: "The shipping city of the order"
      - name: ship_state_province
        description: "The shipping state or province of the order"
      - name: ship_postal_code
        description: "The shipping postal code of the order"
      - name: ship_country
        description: "The shipping country of the order"
      - name: created_at
        description: "The timestamp of when the record was created"
      - name: updated_at
        description: "The timestamp of when the record was last updated"
  
  - name: stores_bronze
    description: "Example of a store master data schema"
    columns:
      - name: store_id
        description: "The primary key for this table, represents a unique store"
      - name: store_name
        description: "The name of the store"
      - name: store_type
        description: "The type of the store"
      - name: address
        description: "The address of the store"
      - name: city
        description: "The city of the store"
      - name: state_province
        description: "The state or province of the store"
      - name: postal_code
        description: "The postal code of the store"
      - name: country
        description: "The country of the store"
      - name: phone
        description: "The phone number of the store"
      - name: email
        description: "The email address of the store"
      - name: is_active
        description: "Flag to indicate if the record is active"
      - name: store_manager
        description: "The name of the store manager"
      - name: created_at
        description: "The timestamp of when the record was created"
      - name: updated_at
        description: "The timestamp of when the record was last updated"
      - name: deleted_at
        description: "The timestamp of when the record was deleted"
  - name: loyalty_bronze
    description: "Example of a loyalty program schema"
    columns:
      - name: loyalty_id
        description: "The primary key for this table, represents a unique loyalty program"
      - name: cust_id
        description: "The foreign key to the customer table"
      - name: program_name
        description: "The name of the loyalty program"
      - name: enrollment_tmstp
        description: "The date the customer enrolled in the loyalty program"
      - name: current_points_balance
        description: "The current points balance of the customer"
      - name: tier_level
        description: "The tier level of the customer"
      - name: created_at
        description: "The timestamp of when the record was created"
      - name: updated_at
        description: "The timestamp of when the record was last updated"
      - name: deleted_at
        description: "The timestamp of when the record was deleted"

  - name: campaigns_bronze
    description: "Example of a campaign schema"
    columns:
      - name: campaign_id
        description: "The primary key for this table, represents a unique campaign"
      - name: campaign_name
        description: "The name of the campaign"
      - name: campaign_description
        description: "The description of the campaign"
      - name: start_date
        description: "The start date of the campaign"
      - name: end_date
        description: "The end date of the campaign"
      - name: campaign_type
        description: "The type of the campaign"
      - name: channel
        description: "The channel of the campaign"
      - name: campaign_status
        description: "The status of the campaign"
      - name: created_at
        description: "The timestamp of when the record was created"
      - name: updated_at
        description: "The timestamp of when the record was last updated"
      - name: deleted_at
        description: "The timestamp of when the record was deleted"