SELECT
    CAST("STORE_ID" AS VARCHAR(25)) AS "STORE_ID",
    CAST("STORE_NAME" AS VARCHAR(100)) AS "STORE_NAME",
    CAST("STORE_TYPE" AS VARCHAR(50)) AS "STORE_TYPE",
    CAST("ADDRESS" AS VARCHAR(100)) AS "ADDRESS",
    CAST("CITY" AS VARCHAR(75)) AS "CITY",
    CAST("STATE_PROVINCE" AS VARCHAR(75)) AS "STATE_PROVINCE",
    CAST("POSTAL_CODE" AS VARCHAR(25)) AS "POSTAL_CODE",
    CAST("COUNTRY" AS VARCHAR(75)) AS "COUNTRY",
    CAST("PHONE" AS VARCHAR(25)) AS "PHONE",
    CAST("EMAIL" AS VARCHAR(75)) AS "EMAIL",
    CAST("IS_ACTIVE" AS BOOLEAN) AS "IS_ACTIVE",
    CAST("STORE_MANAGER" AS VARCHAR(75)) AS "STORE_MANAGER",
    CAST("CREATED_AT" AS TIMESTAMP) AS "CREATED_AT",
    TRY_CAST("UPDATED_AT" AS TIMESTAMP) AS "UPDATED_AT",
    TRY_CAST("DELETED_AT" AS TIMESTAMP) AS "DELETED_AT"
FROM {{ source('stores_raw', 'storesynthdata') }}